### ISSUE TITLE
The component generator doesn't work without generator-react-webpack

### ISSUE THREAD

**Issue by stylesuxx** [weblogixx/generator-react-webpack-alt#5]
This is a cross post from my [redux generator](https://github.com/stylesuxx/generator-react-webpack-redux/issues/2) but also affects this generator.

Fix is [quite simple](https://github.com/stylesuxx/generator-react-webpack-redux/commit/18201d4c3b7419a8df67a4d35d3e542d24cdb8e5).

Let me know If I should supply a PR.

**Comment by weblogixx** [comment]
Hi @stylesuxx,

Just added your fix to the source. Did not even try to use it without the parent project installed globally :(.
Thank you for the fix and feedback!
