### ISSUE TITLE
Update main in package.json to app/index.js?

### ISSUE THREAD

**Issue by sthzg** [weblogixx/generator-react-webpack-alt#7]
hi @weblogixx, I just tried to install the generator from a local copy and noticed that 
`$ yo ./node_modules/generator-react-webpack-alt` triggers `generators/action/index.js`. When setting`main` in `package.json` to `generators/app/index.js` the local install works. If that change doesn't break other behavior it might be worth an update.

**Comment by weblogixx** [comment]
Hi, thank you for the hint. Same would go for the parent project I think. Will update both this weekend.

A new release will be made nect week, reacts new major is out :-)

**Comment by sthzg** [comment]
Wow, no more `data-reactid` or unnecessary `<span />'s`. And also `suppressContentEditableWarning`. Still I think I'll give it another few days until I'll expose myself to that  `npm update` adrenalin rush. :) Hope you have good time updating the generators.

**Comment by weblogixx** [comment]
Yes, seems to run nicely. Just updated the generator with your provided fix and the template to use react 15.0.1. hope it works correctly for you now.
